name = "sikuning"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "166b4635-1d63-40a1-abe5-5b1e28eccb89"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
